### ISSUE TITLE
Clarifications on ordering process

### ISSUE THREAD

**Issue by karthikvenkatak** [harish-seetamraju/yum-kfc#34]
1.**Sum of stores ordering on d, d-1 and d-2 will not be equal to 4k (total number of stores)** 
For example, if we consider W750243, it orders on Monday and Thursday. For this store, we will not have d/d-1/d-2 order on friday. If business requests to have store orders every day, then we might need to create d-3 order as well (for above example) to cater to that request. Need confirmation if d-1 and d-2 orders are sufficient.

2. Order simulation process --> **Should we take the ending count from inventory table at the start of every period to make apples to apples comparison?**
For example, while generating results for P1 period, we take the ending count for both tiger and RGM simulation from the inventory table.Hence we are starting off from same base. But for P2, the ending count for RGM and Tiger simulation starts off with a different base (since we take the simulated ending count (obtained at the end of p1) for tiger and rgm).   

3. **Do we need D-2 order when there is an overlap of previous order on the same day**
For example, if a store has an order cycle on Monday and Wednesday, 
d-2 order for Wednesday's order will overlap with Monday's order. Will RGM use d-2 order in this case?

**Comment by gauthammn** [comment]
Hi Karthik,

Summarized below are what we discussed on these 3 items.

1. If it's not significant effort to extend code to include d-3 then it would be better to do that since KFC is expecting to have an order recommendation available daily.

2. Taking ending count from inventory table at the beginning of each period is a good idea. We can do that.

3. Given that there are not a lot of stores where this happens, I think we can just keep the process standardized instead of customizing for different stores.

**Comment by harish-seetamraju** [comment]
@vinayTA spoke to chenchen and d-3 is not required. to be confirmed with KFC.

#2 and #3 are complete.
