### ISSUE TITLE
Need additional column in stg_order_output_comparison table

### ISSUE THREAD

**Issue by karthikvenkatak** [harish-seetamraju/yum-kfc#37]
Need an additional column for stg_order_output_comparison table:
Actual order (purchase unit) = (derived theoretical usage (counting unit) - ohq (counting unit))/(measuring unit or UOM)

**Comment by prashanththang** [comment]
Hi @karthikvenkatak @vinayTA @harish-seetamraju ,

The following are the changes on chicken ordering logic for order comparison table:

1) Chicken order buffer = 'required quantity for 29692  (in stg_order_output table)'/ 20
2) Chicken order JIT = ((29693 order (21 hd dark) *21)+(29692 (8 pc purple) *20))/20

Thanks,
Prashanth

**Comment by prashanththang** [comment]
@karthikvenkatak @vinayTA @harish-seetamraju ,

The changes are implemented. Please find the details regarding the order comparison table.

1) Derived theoritical is calculated from item level to inventory level roll up 
2) RGM Invoices is captured for a order delivery date and for a delivery date which is delayed by one day (corner case)
3) Chicken GIN 29693 not is taken into consideration.
4) Store period is added to table.
5) Actuals order is calculated by derived theoretical usage - ohq 
6) The order comparison table will be updated on a 10 day lag since actuals for (item qty and inventory date) JIT period for daily/ weekly items should be updated. This will be part of daily schedule, example : if we pass rundate : 2020-05-29 to the script, order generated as of 2020-05-19 will be taken and order comparison table is created and pushed to DB for 2020-05-19
7) Column names are aligned with schema details excel provided. 
8) Actuals orders are for JIT period.
9) Non recipe inventories are removed.
10) In terms of implementing chicken orders, the result from stg_order_output uses Nigels's logic and hence the following change was implemented : 
--- Chicken order buffer = 'required quantity for 29692 (in stg_order_output table)'/ 20
--- Chicken order JIT = ((29693 order (21 hd dark) *21)+(29692 (8 pc purple) *20))/20
