### ISSUE TITLE
Changes in restaurant ownership in March 2020

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#8]
Some restaurants were converted from Fran to Corp. and some from Corp. to Fran in March. These changes would have implications how we read data for these restaurants each time (either in piepline or for adhoc analysis). For a particular physical restaurant, all chned_str_ids to should be consolidated to report data.

Changes are in the attached file for reference

[200403_KFCC Sites.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4454934/200403_KFCC.Sites.xlsx)

**Comment by harish-seetamraju** [comment]
@vinayTA Can you update if this is taken care of everywhere in the pipeline and reporting?

**Comment by kiranrokkams** [comment]
Changes here are dynamic. When a change of ownership happens all subsequent datapoint will be reported at new chain_store_id level. For March actuals, since execution happened recently it should have been accounted. Can someone in consulting query aurora DB for chainstore and max createdatetime in all tables and verify?

**Comment by harish-seetamraju** [comment]
@karthikvenkatak Can you validate this ad close?

**Comment by karthikvenkatak** [comment]
I verified this. We have the stores with new chain store id in aurora db tables
